.open fall21.db
.headers on
.mode csv
.output fall21.csv
SELECT * FROM DECSCI
UNION ALL
SELECT * FROM ARABIC
UNION ALL
SELECT * FROM CHINESE
UNION ALL
SELECT * FROM AAAS
UNION ALL
SELECT * FROM CELLBIO
UNION ALL
SELECT * FROM ECON
UNION ALL
SELECT * FROM DOCST
UNION ALL
SELECT * FROM AADS
UNION ALL
SELECT * FROM CESC
UNION ALL
SELECT * FROM ARTHIST
UNION ALL
SELECT * FROM CINE
UNION ALL
SELECT * FROM AEROSCI
UNION ALL
SELECT * FROM EDUC
UNION ALL
SELECT * FROM CLST
UNION ALL
SELECT * FROM COMPSCI
UNION ALL
SELECT * FROM ARTSVIS
UNION ALL
SELECT * FROM ECE
UNION ALL
SELECT * FROM BIOLOGY
UNION ALL
SELECT * FROM EHD
UNION ALL
SELECT * FROM AMES
UNION ALL
SELECT * FROM CREOLE
UNION ALL
SELECT * FROM CMAC
UNION ALL
SELECT * FROM BIOCHEM
UNION ALL
SELECT * FROM ECS
UNION ALL
SELECT * FROM ENERGY
UNION ALL
SELECT * FROM BME
UNION ALL
SELECT * FROM GREEK
UNION ALL
SELECT * FROM ENGLISH
UNION ALL
SELECT * FROM EOS
UNION ALL
SELECT * FROM FRENCH
UNION ALL
SELECT * FROM CULANTH
UNION ALL
SELECT * FROM ENRGYEGR
UNION ALL
SELECT * FROM GENOME
UNION ALL
SELECT * FROM GSF
UNION ALL
SELECT * FROM ETHICS
UNION ALL
SELECT * FROM DANCE
UNION ALL
SELECT * FROM HEBREW
UNION ALL
SELECT * FROM GERMAN
UNION ALL
SELECT * FROM EGR
UNION ALL
SELECT * FROM HISTORY
UNION ALL
SELECT * FROM BRAINSOC
UNION ALL
SELECT * FROM CHEM
UNION ALL
SELECT * FROM EVANTH
UNION ALL
SELECT * FROM HINDI
UNION ALL
SELECT * FROM IMMUNOL
UNION ALL
SELECT * FROM GLHLTH
UNION ALL
SELECT * FROM HOUSECS
UNION ALL
SELECT * FROM CEE
UNION ALL
SELECT * FROM CHILDPOL
UNION ALL
SELECT * FROM JEWISHST
UNION ALL
SELECT * FROM FOCUS
UNION ALL
SELECT * FROM LATAMER
UNION ALL
SELECT * FROM LSGS
UNION ALL
SELECT * FROM HUMANDEV
UNION ALL
SELECT * FROM PERSIAN
UNION ALL
SELECT * FROM JPN
UNION ALL
SELECT * FROM MEDREN
UNION ALL
SELECT * FROM LATIN
UNION ALL
SELECT * FROM MARSCI
UNION ALL
SELECT * FROM KICHE
UNION ALL
SELECT * FROM ENVIRON
UNION ALL
SELECT * FROM MGM
UNION ALL
SELECT * FROM LINGUIST
UNION ALL
SELECT * FROM PHARM
UNION ALL
SELECT * FROM KOREAN
UNION ALL
SELECT * FROM MILITSCI
UNION ALL
SELECT * FROM PHYSICS
UNION ALL
SELECT * FROM LIT
UNION ALL
SELECT * FROM ROMST
UNION ALL
SELECT * FROM PHIL
UNION ALL
SELECT * FROM MUSIC
UNION ALL
SELECT * FROM MMS
UNION ALL
SELECT * FROM PJMS
UNION ALL
SELECT * FROM SES
UNION ALL
SELECT * FROM RUSSIAN
UNION ALL
SELECT * FROM SUSTAIN
UNION ALL
SELECT * FROM NAVALSCI
UNION ALL
SELECT * FROM PHYSEDU
UNION ALL
SELECT * FROM MATH
UNION ALL
SELECT * FROM PSY
UNION ALL
SELECT * FROM SANSKRIT
UNION ALL
SELECT * FROM SXL
UNION ALL
SELECT * FROM SOCIOL
UNION ALL
SELECT * FROM TURKISH
UNION ALL
SELECT * FROM SWAHILI
UNION ALL
SELECT * FROM SCISOC
UNION ALL
SELECT * FROM UNIV
UNION ALL
SELECT * FROM POLSCI
UNION ALL
SELECT * FROM THEATRST
UNION ALL
SELECT * FROM SPANISH
UNION ALL
SELECT * FROM PORTUGUE
UNION ALL
SELECT * FROM PUBPOL
UNION ALL
SELECT * FROM NEUROSCI
UNION ALL
SELECT * FROM VMS
UNION ALL
SELECT * FROM STA
UNION ALL
SELECT * FROM PATHOL
UNION ALL
SELECT * FROM RELIGION
UNION ALL
SELECT * FROM WRITING
UNION ALL
SELECT * FROM RIGHTS
UNION ALL
SELECT * FROM INTERNATL
UNION ALL
SELECT * FROM ISS
UNION ALL
SELECT * FROM IE
UNION ALL
SELECT * FROM ITALIAN
UNION ALL
SELECT * FROM MECH;
